### ISSUE TITLE
Error after clicking Login

### ISSUE THREAD

**Issue by thekennysong** [prabhuignoto/boxy#20]
I am getting http://localhost:4000/auth/undefined/?client_id=&redirect_uri=&response_type=code after clicking login. Assuming issue with my server config or something locally, has anyone run into this? Love the repo btw!

Edit: I had to put in a .env file (I have .env.development and .env.production). How can I get to work with the specific env files?

**Comment by prabhuignoto** [comment]
@thekennysong thanks for your feedback.

I'm attaching the env files that i use locally with the app secrets removed. Give it a try and let me know how it goes.
[env files.zip](https://github.com/prabhuignoto/boxd/files/5069403/env.files.zip)
